### PR TITLE
Add Solr Power indexing on multidev creation example

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by ataylorme** [comment]
Solr Power doesn't post `schema.xml` to multidev environments unless the WordPress dashboard is visited. This caused errors when attempting to index with wp-cli after multidev creation via Quicksilver. Schema now gets posted before and index happens and all is well.

**Comment by aeligature** [comment]
+1 tested, works pretty good to me!

**Comment by greg-1-anderson** [comment]
This PR contains two sets of the same files: one set in solr_index, and the other in wp_solr_index.  Only one of these should exist -- I suggest the later.

**Comment by ataylorme** [comment]
> This PR contains two sets of the same files: one set in solr_index, and the other in wp_solr_index. Only one of these should exist -- I suggest the later.

That's my fault @greg-1-anderson - I didn't git remove the old files. Updated now - thanks for catching that.

**Comment by ari-gold** [comment]
@ataylorme Would you mind squashing and rebasing?

**Comment by ataylorme** [comment]
@ari-gold Can't you squash on merge?

**Comment by greg-1-anderson** [comment]
Github has that feature now!  We cannot use the big green button on some repositories, but it should work fine here.

+1 LGTM 🚀

**Comment by ari-gold** [comment]
@ataylorme Ah, yes I can! Thanks for the awesome contribution.

**Pull request merged**
