### PR TITLE
Factor out slack_lib, and do better error checking on secrets file.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
The other script needs to be refactored, and needs testing, but here's the general idea.

### CODE REVIEW

**Comment by bmackinney** [comment]
:+1:

**Comment by marktheunissen** [comment]
This is a slippery slope! :warning:

**Comment by joshkoenig** [comment]
-1 for this. We need to not get ahead of ourselves here.

Right now the goal of this example is to provide a simple self-contained script that does one job. The language is PHP, but the mindset should be "what would a bash script do?"

**Comment by greg-1-anderson** [comment]
Okay, I am going to roll this back.

**Pull request merged**
