### PR TITLE
Drush example

### PR DESCRIPTION
**Pull request by mikemilano**
An example that shows drush executed with `shell_exec()` in conjunction with `--format=json` on the drush command, as well as a simple `passthru()`.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Great example. Have not tested it yet, but +1 on code and docs.

**Comment by joshkoenig** [comment]
@greg-1-anderson can you test and merge if this works as expected?

**Comment by greg-1-anderson** [comment]
Works great; thanks!  Renamed to 'enable dev modules' and merged.

**Comment by greg-1-anderson** [comment]
Hi Ruby,

Is the `devel` module enabled in your test and live environments?  The general intention here is that you should have `devel` enabled in your dev and multidev environments, but not in test and live.  The "enabled" state of a module is stored in the database, so copying the database from test to dev disabled the devel module.  This Quicksilver example re-enables it again.

**Pull request merged**
