### PR TITLE
Hipchat notification

### PR DESCRIPTION
**Pull request by mikemilano**
Similar to the slack_notification example, but for hipchat. I formatted the messages to look more like the default Atlassian integrations for their repo products and hipchat.

hipchat_notification

Note: the `Ansible` text in the screenshot comes from the token name on the hipchat side, not this example itself. Just an existing token I was testing with.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Overall looks good.  See #37, as any refactor that we do over there should also be applied similarly over here.

**Comment by joshkoenig** [comment]
Let's refactor this to use one script. Also use the `deploy_message` part of the payload instead of git-fu to get the message for deploys.

**Comment by joshkoenig** [comment]
Also, too, we'll have before/after as the `stage` key in the `$_POST` payload shortly. We should have this and Slack using that. :)

**Comment by greg-1-anderson** [comment]
Continued in #54.

**Pull request closed without merging**
