### PR TITLE
Revert all features

### PR DESCRIPTION
**Pull request by Gfriedman21**
Made an example of integrating a drush command into a quicksilver operation. This operation will revert all of the features before deploying to test or live.

### CODE REVIEW

**Comment by bthompson-mindgrub** [comment]
If we're going to use Drush to revert all features why don't we also use it to test for the features module?  Then we don't need to worry about which version of Drupal is being used because Drush abstracts all of that away from us.

Something like (I'm mixing PHP and command line here just for the sake of demonstration):
```
$modules = drush pm-list --status=enabled --format=json;
$modules = json_decode($modules);
if (in_array('features', $modules)) {
  // Revert all features
}
```

**Comment by greg-1-anderson** [comment]
The issue is that you cannot simple `exec` Drush from a `webphp` script. Some things might happen to work, but the example here cannot easily be extended, because it makes no attempt to bootstrap Drush, and only pulls in the minimum files needed for the feature revert to work.  I'm actually kind of surprised that it works!  (Disclaimer: have not tried it.)

The best thing would be to have a `drush` workflow, to complement `webphp`. Then, folks could simply write custom Drush commands and attach them to their modules for any operation that required sequences of Drush commands, or operations on a bootstrapped Drupal site.

**Comment by bthompson-mindgrub** [comment]
FWIW -- I'm not overly convinced it does work and here's why:

There is no bootstrap of Drupal in the included code so the only variables you have outside of what is in this script are the ones from the required `code/includes/module.inc` and the Drush file.  I didn't dive into those 2 files to see which files they include/require to know if they bring in other Drupal files.  Drupal 8 defines a `CORE_COMPATIBILITY` constant in `core/lib/Drupal.php` (https://github.com/drupal/drupal/blob/8.0.x/core/lib/Drupal.php#L89).  Drupal 7 does not define a `CORE_COMPATIBILITY` constant (that I could find) but does define a `DRUPAL_CORE_COMPATIBILITY` constant (https://github.com/drupal/drupal/blob/7.x/includes/bootstrap.inc#L16).  The check of whether or not `CORE_COMPATIBILITY` is defined or not is a bit shaky if Drupal 9 were to define this same variable (and even then, I'm still not convinced this would be defined for a Drupal 8 site because `code/includes/module.inc` wouldn't exist on a D8 site.

I like the idea of having a `drush` workflow.  Inherently, it seems like that would also necessitate a `wpcli` workflow as well so we don't leave our WP friends behind.  I'm not sure what the timeline for rolling additional workflows like `drush` would be.  I'm guessing the system on the Pantheon side is fairly flexible (based on all the other Pantheon systems I've seen) but still involves a bit of effort to support.

In the short term, if this were to move forward I think the following (at a minimum) would need to be done:

1.  Split the example into 2 versions -- one for D7 and one for D8 similar to how there is a Drupal and WP version of `db_sanitization`
2.  In each of the new examples, bootstrap Drupal (also similar to what the db_sanitization example does) and then use Drupal/features modules native functions to do the revert.  The fact that we have to bootstrap Drupal fully is a bit unfortunate, but would ultimately be the same thing as what Drush would be doing if this were to be done with drush.

**Comment by joshkoenig** [comment]
> I like the idea of having a drush workflow. Inherently, it seems like that would also necessitate a wpcli workflow as well so we don't leave our WP friends behind.

FWIW this is definitely on the roadmap, but I wouldn't let it block anyone from building examples that "manually bootstrap" Drupal/WP now.

**Comment by Gfriedman21** [comment]
I updated the code to fully bootstrap Drupal and revert all features. This code works with Drupal 7 and uses the current stable Features module (7.x-2.7).

**Comment by greg-1-anderson** [comment]
FYI, it is now possible to call `drush` directly from a webphp script, so this could probably just be `passthru("drush fra");` or perhaps something a little more complicated than that.

**Comment by stevector** [comment]
I'm testing passthru with a single feature and it is working. `passthru('drush fr name_of_feature_module -y');`

**Comment by bthompson-mindgrub** [comment]
I'll run a test with a `passthru('drush fra');` when I'm back in the office tomorrow.  Thanks @greg-1-anderson for working on this!

**Comment by stevector** [comment]
@bthompson-mindgrub don't forget the `-y`! `passthru('drush fra -y');`

**Comment by dbouman** [comment]
I can confirm, using passthru('drush fra -y'); worked for me!

**Comment by bthompson-mindgrub** [comment]
Thanks @dbouman!

@Gfriedman21 can you update this PR when you have a minute with the new passthru?  Reference what we have in our D7 upstream in BitBucket for Pantheon.

**Comment by Gfriedman21** [comment]
Updated PR using passthru to call the drush commands.

**Comment by davidstrauss** [comment]
Is there no way to invoke a Drush command without using a passthru shell command?

**Comment by greg-1-anderson** [comment]
In another issue I did propose introducing a Drush API that could be called directly from scripts such as Quicksilver webhooks. However, even Drush itself favors using exec to call Drush functionality, e.g. via `drush_invoke_process()`, so atm doing this is the most straightforward way.

**Comment by greg-1-anderson** [comment]
Nice. +1

**Comment by joshkoenig** [comment]
@davidstrauss this is the result of us scoping initial implementation to provide only a `webphp` operation. Future updates should include first-class operations once we feel like we can support the task-runners at scale.

**Comment by joshkoenig** [comment]
This is great. Works as advertised. I'm going to pull it in and then make some tweaks to re-name the directory and wordsmith the readme.

**Pull request merged**
