### PR TITLE
Example of automatically importing settings for wordpress

### PR DESCRIPTION
**Pull request by gmcinnes**
Use wp-cfm and it's wp-cli integration to automatically import settings after db-clone

### CODE REVIEW

**Comment by stevector** [comment]
@ataylorme, can you look at this PR?

**Comment by ataylorme** [comment]
Hi @gmcinnes,
It looks like WP-CFM tagged version `1.4.4` today. Can you update `README.md` so that the installation instructions direct users to install the plugin from the WordPress plugin repository, instead of GitHub?

I'm going to run through the steps on a test site now and will let you know if I run into any issues.

**Comment by ataylorme** [comment]
Hi @gmcinnes,
After reviewing I see one major issue. The wp-cfm filters are `wpcfm_config_dir` and `wpcfm_config_url` *not* `wpcfm_content_dir` and `wpcfm_content_url` (_config_ not _content_). 

See [wp-cfm.php](https://github.com/forumone/wp-cfm/blob/master/wp-cfm.php#L45:L46) on GitHub. Can you update `alter_wpcfm_config_path.php`?

I also think steps under _Creating a WP-CFM configuration file_ in the `README.md` can be simplified. I was able to:
1) Put your site into sftp mode.
2) Clone your database from the live environment.
3) Create a wp-cfm bundle, tracking all the options, and push it to the filesystem.
4) Make the changes you want to see in your development site.
5) Use the diff functionality to compare the saved bundle with the current state of the database.
6) Update the wp-cfm bundle to track only the options that changed in step 5.
7) Push the bundle to the filesystem.
8) Commit the new bundle files in the Pantheon dashboard.
9) Put your site back into git mode.

Other than that this looks great!

**Comment by gmcinnes** [comment]
@ataylorme Thank you so much.  It's so nice to have a good, thoughtful, reviewer.

I've made the changes you suggested.

**Comment by ataylorme** [comment]
> Thank you so much. It's so nice to have a good, thoughtful, reviewer.
> I've made the changes you suggested.

@gmcinnes - Awesome! Thanks for the quick turn around and your contribution.

**Pull request merged**
